### Get All Contacts
GET http://localhost:3000/contacts
Content-Type: application/json

###

### Get Single Contact by ID
GET http://localhost:3000/contacts/6a47207eff0f3c607b648549
Content-Type: application/json

###

### Base URL Check
GET http://localhost:3000/
Content-Type: application/json